spring:
  application:
    name: hello-client
  datasource:
    url: jdbc:postgresql://localhost:5432/fasdb?currentschema=ms1
    username: root
    password: root
  jpa:
    properties:       hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:      ddl-auto: update    show-sql: true
  zipkin:
    base-url: http://localhost:9411/


    
    
server:
  port: 8002
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
